require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  Include:
    - 'app/**/*.rb'
  # Exclude:
  #   - 'bin/**/*'
  #   - 'db/**/*'
  #   - 'config/**/*'
  #   - 'spec/**/*'

Style/Documentation:
  Enabled: false

Rails:
  Enabled: true

# There is a bug in the Rubocop 0.48 parser that causes it to incorrectly
# complain about parentheses around blocks used with scopes. This should be
# removed once it is possible to upgrade to 0.49 or above.
# Lint/AmbiguousBlockAssociation:
#   Enabled: false

# Rubocop should be used for style guide adherence, not testing for code smell
# Rails/OutputSafety:
#   Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false
#
# Rails/InverseOf:
#   Enabled: false
#
# Rails/HasManyOrHasOneDependent:
#   Enabled: false
#
# Rails/HelperInstanceVariable:
#   Enabled: false
#
# Style/MixinUsage:
#   Enabled: false
#
# Layout/EmptyLineAfterMagicComment:
#   Enabled: false
#
# Metrics/PerceivedComplexity:
#   Enabled: false
#
# Metrics/CyclomaticComplexity:
#   Enabled: false
#
# Metrics/AbcSize:
#   Enabled: false
#
# Style/HashEachMethods:
#   Enabled: true
#
# Style/HashTransformKeys:
#   Enabled: true
#
# Style/HashTransformValues:
#   Enabled: true
